# Generated by Django 2.0.5 on 2018-05-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ART_MANIAC_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',), 'verbose_name': ('category',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product',)},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='DEFAULT', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='ART_MANIAC__id_d38e57_idx'),
        ),
    ]
